<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Document</title>
    <link href="/webroot/css/bootstrap.css" rel="stylesheet">
    <link href="/webroot/css/styleAdd.css" rel="stylesheet">
</head>
<body>
<div class="container-fluid fon">

    <h1 class="text-center py-4">Форма добавления статьи</h1>
    <?php use Library\Session;?>

    <div class="alert small text-center" style="font-size: 25px; color: #31ff4a;"><b><?=Session::getFlash()?></b></div>

    <form method="post" class="row">
        <div class="col-4">
        <input class="row_input mb-2 text-white" placeholder="Название" id='nameShip' type="text" name="nameShip"><br>
        <input class="row_input mb-2 text-white" placeholder="Длинна" id='longShip' type="text" name="longShip"><br>
        <input class="row_input mb-2 text-white" placeholder="Ширина" id='widthShip' type="text" name="widthShip"><br>
        <input class="row_input mb-2 text-white" placeholder="Высота" id='heightShip' type="text" name="heightShip"><br>
        <input class="row_input mb-2 text-white" placeholder="Водоизмищение" id='displacement' type="text" name="displacement"><br>
        <input class="row_input mb-2 text-white" placeholder="Спуск на воду" id='launching' type="text" name="launching"><br>
        <input class="row_input mb-2 text-white" placeholder="Вывод из эксплуатации" id='removalFromService' type="text" name="removalFromService">
        </div>
        <div class="col-8 pb-2 pl-0">
        <textarea class="description text-white" placeholder="Описание корабля"  id='description' name="description"></textarea>
        </div>
        <div class="col text-center">
        <button class="btn px-5 py-2 mt-3 mb-5">Отправить</button>
        </div>
    </form>
</div>

</body>
</html>