<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Document</title>
    <link href="/webroot/css/bootstrap.css" rel="stylesheet">
    <link href="/webroot/css/styleAdminAdd.css" rel="stylesheet">
</head>
<body>
<div class="container-fluid fon">

    <h1 class="text-center pt-4">Форма добавления статьи</h1>



    <form method="post">
        <input class="name" placeholder="Название" id='username' type="text" name="username"><br>
        <input class="email mt-4" placeholder="Длинна" id='email' type="text" name="email">
        <input class="email mt-4" placeholder="Ширина" id='email' type="text" name="email"><br>
        <input class="email mt-4" placeholder="Высота" id='email' type="text" name="email"><br>
        <input class="email mt-4" placeholder="Водоизмищение" id='email' type="text" name="email"><br>
        <input class="email mt-4" placeholder="Спуск на воду" id='email' type="text" name="email"><br>
        <input class="email mt-4" placeholder="Вывод из эксплуатации" id='email' type="text" name="email"><br>
        <textarea class="comment mt-4" placeholder="Описание корабля"  id='message' name="message"></textarea><br>
        <button class="btn btn-primary px-5 py-2 mt-3">Отправить</button>
    </form>
</div>

</body>
</html>