<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Document</title>
    <link href="/webroot/css/bootstrap.css" rel="stylesheet">
    <link href="/webroot/css/style.css" rel="stylesheet">
</head>
<body>
<div class="container-fluid my-0">
    <div class="container header my-0">
        <h4 class="title_1 lead"><b>Добро пожаловать!</b></h4>
        <p class="title_2 lead"><b>Энциклопедия кораблей</b></p>
        <p class="title_3 lead w-50 text-center">На данном сайте вы можете найти описание и технические характеристики извесных кораблей.</p>
    </div>
    <div class="container m-0">
        <div class="titleGallery">
            <h1 class="text-center py-5 m-0" style="color: #fff;">Галлерея самых известных судов</h1>
        </div>
        <div class="borderGallery text-center">
            <div class="row ml-4 my-5">
                <div class="col">
                    <div class="gallery">
                        <img src="/webroot/img/QueenMary2_1.jpg" alt="" height="200px" width="300px">
                        <h3 class="my-2" style="color: #fff">Queen Mary 2</h3>
                    </div>
                </div>
                <div class="col">
                    <div class="gallery">
                        <img src="/webroot/img/Allure-of-the-Seas_1.jpg" alt="" height="200px" width="300px">
                        <h3 class="my-2" style="color: #fff">Allure of the Seas</h3>
                    </div>
                </div>
                <div class="col">
                    <div class="gallery">
                        <img src="/webroot/img/Oasis%20of%20the%20Seas_1.jpg" alt="" height="200px" width="300px">
                        <h3 class="my-2" style="color: #fff">Oasis of the Seas</h3>
                    </div>
                </div>
            </div>


            <div class="row ml-4 my-5">
                <div class="col">
                    <div class="gallery">
                        <img src="/webroot/img/Ellie%20Lady.jpg" alt="" height="200px" width="300px">
                        <h3 class="my-2" style="color: #fff">Ellie Lady</h3>
                    </div>
                </div>
                <div class="col">
                    <div class="gallery">
                        <img src="/webroot/img/Hellespont_alhambra.jpg" alt="" height="200px" width="300px">
                        <h3 class="my-2" style="color: #fff">Hellespont Alhambra</h3>
                    </div>
                </div>
                <div class="col">
                    <div class="gallery">
                        <img src="/webroot/img/vale_brasil.jpg" alt="" height="200px" width="300px">
                        <h3 class="my-2" style="color: #fff">Vale Brasil</h3>
                    </div>
                </div>
            </div>


            <div class="row ml-4 my-5">
                <div class="col">
                    <div class="gallery">
                        <img src="/webroot/img/Midway.jpg" alt="" height="200px" width="300px">
                        <h3 class="my-2" style="color: #fff">Midway</h3>
                    </div>
                </div>
                <div class="col">
                    <div class="gallery">
                        <img src="/webroot/img/Ranvir.jpg" alt="" height="200px" width="300px">
                        <h3 class="my-2" style="color: #fff">Ranvir</h3>
                    </div>
                </div>
                <div class="col">
                    <div class="gallery">
                        <img src="/webroot/img/miccury.jpg" alt="" height="200px" width="300px">
                        <h3 class="my-2" style="color: #fff">Missouri</h3>
                    </div>
                </div>
            </div>


            <div class="row ml-4 my-5">
                <div class="col">
                    <div class="gallery">
                        <img src="/webroot/img/normandiya.jpg" alt="" height="200px" width="300px">
                        <h3 class="my-2" style="color: #fff">Normandie</h3>
                    </div>
                </div>
                <div class="col">
                    <div class="gallery">
                        <img src="/webroot/img/titanic.jpg" alt="" height="200px" width="300px">
                        <h3 class="my-2" style="color: #fff">Titanic</h3>
                    </div>
                </div>
                <div class="col">
                    <div class="gallery">
                        <img src="/webroot/img/Wilhelm_Gustlofff.jpg" alt="" height="200px" width="300px">
                        <h3 class="my-2" style="color: #fff">Wilhelm Gustloff</h3>
                    </div>
                </div>
            </div>


            <div class="row ml-4 mb-5">
                <div class="col">
                    <div class="gallery">
                        <img src="/webroot/img/Sedov.jpg" alt="" height="200px" width="300px">
                        <h3 class="my-2" style="color: #fff">Sedov</h3>
                    </div>
                </div>
                <div class="col">
                    <div class="gallery">
                        <img src="/webroot/img/Royal_Clipper.jpg" alt="" height="200px" width="300px">
                        <h3 class="my-2" style="color: #fff">Royal Clipper</h3>
                    </div>
                </div>
                <div class="col">
                    <div class="gallery">
                        <img src="/webroot/img/AmerigoVespucci.jpg" alt="" height="200px" width="300px">
                        <h3 class="my-2" style="color: #fff">Amerigo Vespucci</h3>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>
</body>
</html>