<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>MVC admin</title>
    <link href="/webroot/css/bootstrap.css" rel="stylesheet">
</head>
<body>
<body>
<div class="container-fluid m-0 p-0" style="padding-top: 100px;">
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #170629;">
        <img src="/webroot/img/logo.png" class="m-0 p-0" width="40">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent" style="1000px">
            <ul class="navbar-nav my-2">
                <li class="nav-item active ml-5">
                    <a href="/admin" style="color: red;">Админка</a>
                </li>
                <li class="nav-item active mx-4">
                    <a href="/admin/ships" style="color: red;">Корабли</a>
                </li>
                <li class="nav-item">
                    <a href="/logout" style="color: red;">Выйти</a>
                </li>
            </ul>
        </div>
    </nav>
</div>

<?=$content?>
<div style="background-color: #170629">
    <img src="/webroot/img/logo.png" class="ml-4 mt-2" width="60">
    <span class="text-primary ml-5"><b>Callback </b></span><span class="text-white"><b>(andrey1988@gmail.com)</b></span>
</div>

</body>
</html>