<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Document</title>
    <link href="/webroot/css/bootstrap.css" rel="stylesheet">
    <link href="/webroot/css/style.css" rel="stylesheet">
</head>
<body>
<div class="container-fluid m-0 p-0" style="padding-top: 100px;">
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #234477;">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent" style="1000px">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a href="/" class="mx-3">Главная</a>
                </li>
                <li class="nav-item">
                    <a href="/ships" class="mx-3">Статьи</a>
                </li>
                <li class="nav-item">
                    <a href="/contact-us" class="mx-3">Контакты</a>
                </li>
                <li class="nav-item">
                    <a href="/login" class="mx-3">Вход</a>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
                <input type="text" class="form-control mr-sm-2" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0">Поиск</button>
            </form>
        </div>
    </nav>
</div>
<b><?=\Library\Session::getFlash()?></b>

<?=$content?>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" crossorigin="anonymous"></script>

</body>
</html>